//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassageApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int id { get; set; }
        public int massage_slot_id { get; set; }
        public int employee_id { get; set; }
        public string phone { get; set; }
        public Nullable<bool> has_attended { get; set; }
        public Nullable<bool> has_paid { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Massage_Slots Massage_Slots { get; set; }
    }
}
