//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MassageApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Massage_Days
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Massage_Days()
        {
            this.Massage_Slots = new HashSet<Massage_Slots>();
        }
    
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string masseuse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Massage_Slots> Massage_Slots { get; set; }
    }
}
